STRUCT_KEYS_REVERSE = {
    "gid": "gid",
    "status": "status",
    "totalLength": "total_length",
    "completedLength": "completed_length",
    "uploadLength": "upload_length",
    "bitfield": "bitfield",
    "downloadSpeed": "download_speed",
    "uploadSpeed": "upload_speed",
    "infoHash": "info_hash",
    "numSeeders": "num_seeders",
    "seeder": "seeder",
    "pieceLength": "piece_length",
    "numPieces": "num_pieces",
    "connections": "connections",
    "errorCode": "error_code",
    "errorMessage": "error_message",
    "followedBy": "followed_by",
    "following": "following",
    "belongsTo": "belongs_to",
    "dir": "dir",
    "files": "files",
    "bittorrent": "bittorrent",
    "announceList": "announce_list",
    "comment": "comment",
    "creationDate": "creation_date",
    "mode": "mode",
    "info": "info",
    "name": "name",
    "verifiedLength": "verified_length",
    "verifyIntegrityPending": "verify_integrity_pending",
}

STRUCT_KEYS = {v: k for k, v in STRUCT_KEYS_REVERSE.items()}
